# Generated by Django 3.1.3 on 2020-12-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configupload',
            name='config_json_file',
            field=models.FileField(blank=True, null=True, upload_to='./vars_json'),
        ),
        migrations.AlterField(
            model_name='configupload',
            name='config_yml_file',
            field=models.FileField(blank=True, null=True, upload_to='./vars_yaml'),
        ),
    ]
