# Generated by Django 3.1.3 on 2020-12-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_generator', '0002_auto_20201206_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='configupload',
            name='tag',
            field=models.CharField(blank=True, choices=[('upload', 'Upload'), ('deploy', 'Deploy'), ('customize', 'Customize')], default='upload', max_length=64, null=True),
        ),
    ]
