# Generated by Django 3.1.3 on 2021-01-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_generator', '0003_configupload_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configupload',
            name='tag',
            field=models.CharField(blank=True, choices=[('audit', 'Audit'), ('deploy', 'Deploy'), ('customize', 'Customize')], default='audit', max_length=64, null=True),
        ),
    ]
