# Generated by Django 3.1.3 on 2021-01-15 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_generator', '0004_auto_20210115_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticVarsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('config_yaml_file', models.FileField(blank=True, null=True, upload_to='./static_vars_yaml')),
                ('tag', models.CharField(blank=True, choices=[('NUTANIX', 'nutanix'), ('VMWARE', 'vmware')], max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
