# Generated by Django 3.1.3 on 2021-05-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_generator', '0008_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
