# Generated by Django 3.1.3 on 2021-05-08 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('playbook_generator', '0009_delete_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='configupload',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
    ]
