# Generated by Django 3.1.3 on 2021-05-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_generator', '0010_configupload_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='configupload',
            name='service_type',
            field=models.CharField(blank=True, choices=[('nutanix', 'NUTANIX'), ('vmware', 'VMWARE')], max_length=64, null=True),
        ),
    ]
