# Generated by Django 3.1.3 on 2021-06-16 01:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20210616_0145'),
        ('playbook_generator', '0012_staticvarsvalue_is_common_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticSiteVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('key', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('site', models.ForeignKey(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
