# Generated by Django 3.1.3 on 2021-06-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_service_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('service_type', 'name')},
        ),
    ]
